name: nnue
dependencies:
  - numpy
  - pandas
  - ipykernel
  - matplotlib
  - pip
  - pip:
    - tensorboard
    - chess
    - zstandard
    - torch
    - torchvision
    - tqdm
    - standard-imghdr
    - torchviz 


# INSTALL: conda env update -f environment.yml